global:
  scrape_interval: 15s  # How often Prometheus scrapes targets

scrape_configs:
  - job_name: 'traefik'
    metrics_path: "/metrics"
    static_configs:
      - targets: ['traefik:8082']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']